# Generated by Django 5.2.17 on 2026-09-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('events', '0002_event_created_by_event_status'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'out')), fields=('equipment',), name='one_active_checkout_per_equipment'),
        ),
    ]
