# Generated by Django 5.2.17 on 2026-09-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_checkout_one_active_checkout_per_equipment'),
        ('events', '0002_event_created_by_event_status'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-checkout_time']},
        ),
        migrations.RemoveConstraint(
            model_name='checkout',
            name='one_active_checkout_per_equipment',
        ),
        migrations.AddConstraint(
            model_name='checkout',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['out', 'overdue'])), fields=('equipment',), name='one_active_checkout_per_equipment'),
        ),
    ]
