# Generated by Django 5.2.17 on 2026-09-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_created_by_event_status'),
        ('members', '0001_initial'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyassignment',
            options={'ordering': ['event__date', 'position__name', 'slot']},
        ),
        migrations.RemoveConstraint(
            model_name='dutyassignment',
            name='one_assignment_per_position',
        ),
        migrations.AddField(
            model_name='dutyassignment',
            name='slot',
            field=models.CharField(default='Main', help_text='Specific duty slot, e.g. Camera 1, Camera 2, Main or Backup.', max_length=100),
        ),
        migrations.AddField(
            model_name='dutyposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dutyposition',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='duty_positions', to='members.skill'),
        ),
        migrations.AlterField(
            model_name='dutyassignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='roster.dutyposition'),
        ),
        migrations.AddConstraint(
            model_name='dutyassignment',
            constraint=models.UniqueConstraint(fields=('event', 'position', 'slot'), name='one_member_per_event_position_slot'),
        ),
    ]
