# Generated by Django 5.2.17 on 2026-09-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_alter_album_options_alter_album_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
